name: Swift Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: swift:5.1

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
